# Generated by Django 5.0.7 on 2025-12-02 09:47

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecorationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات دکوراسیون',
                'verbose_name_plural': 'دسته\u200cبندی خدمات دکوراسیون',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DecorationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='decoration/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تصویر خدمت دکوراسیون',
                'verbose_name_plural': 'تصاویر خدمت دکوراسیون',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecorationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='decoration/', verbose_name='تصویر اصلی')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدت زمان')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='مکان')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='decoration.decorationcategory', verbose_name='دسته\u200cبندی')),
                ('gallery', models.ManyToManyField(blank=True, related_name='decoration_galleries', to='decoration.decorationimage', verbose_name='گالری تصاویر')),
            ],
            options={
                'verbose_name': 'خدمت دکوراسیون',
                'verbose_name_plural': 'خدمات دکوراسیون',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecorationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('decoration_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='decoration.decorationservice', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'استعلام خدمت دکوراسیون',
                'verbose_name_plural': 'استعلام\u200cهای خدمت دکوراسیون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='decorationimage',
            name='decoration_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='decoration.decorationservice', verbose_name='خدمت'),
        ),
    ]
