# Generated by Django 5.0.7 on 2025-12-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کاربر', 'verbose_name_plural': 'پروفایل\u200cهای کاربران'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_job',
            field=models.CharField(blank=True, max_length=200, verbose_name='شغل فعلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='منطقه/محله'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا'), ('other', 'سایر')], max_length=20, verbose_name='آخرین مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_categories',
            field=models.CharField(blank=True, max_length=500, verbose_name='دسته\u200cبندی\u200cهای مورد علاقه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_of_activity',
            field=models.CharField(blank=True, max_length=200, verbose_name='زمینه فعالیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, verbose_name='رشته'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followed_topics',
            field=models.TextField(blank=True, verbose_name='انتخاب موضوعاتی که دنبال می\u200cکند'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_address',
            field=models.TextField(blank=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال فارغ\u200cالتحصیلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='how_did_you_hear',
            field=models.CharField(blank=True, max_length=200, verbose_name='نحوه آشنایی با سایت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='اینستاگرام / شبکه\u200cهای اجتماعی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='سمت شغلی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landline',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_content_type',
            field=models.CharField(blank=True, choices=[('articles', 'مقالات'), ('videos', 'ویدیوها'), ('courses', 'دوره\u200cها'), ('events', 'رویدادها'), ('all', 'همه')], max_length=20, verbose_name='نوع محتوای مورد علاقه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_message_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعات ترجیحی دریافت پیام\u200cها'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='قبول قوانین و حریم خصوصی'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='دانشگاه / موسسه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='وب\u200cسایت شخصی یا کاری'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال\u200cهای تجربه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
    ]
