# Generated by Django 5.0.7 on 2025-11-30 19:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دانشگاه')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='universities/', verbose_name='تصویر')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت (لیر ترکیه)')),
                ('price_note', models.CharField(blank=True, max_length=200, null=True, verbose_name='یادداشت قیمت')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='موقعیت')),
                ('university_type', models.CharField(choices=[('public', 'دولتی'), ('private', 'خصوصی')], default='public', max_length=50, verbose_name='نوع دانشگاه')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='زبان تدریس')),
                ('ranking', models.CharField(blank=True, max_length=100, null=True, verbose_name='رتبه')),
                ('programs', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='رشته\u200cهای تحصیلی')),
                ('admission_requirements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='شرایط پذیرش')),
                ('scholarship_info', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='اطلاعات بورسیه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
