# Generated by Django 5.2.7 on 2025-11-05 11:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='goals/', verbose_name='تصویر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='زیرعنوان')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='تصویر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اسلاید صفحه اصلی',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی خدمات',
                'verbose_name_plural': 'دسته\u200cبندی خدمات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_description', models.TextField(verbose_name='توضیحات سایت')),
                ('site_logo', models.ImageField(upload_to='site/', verbose_name='لوگو')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاویکون')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_1', models.CharField(max_length=20, verbose_name='تلفن ۱')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ۲')),
                ('phone_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ۳')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساپ')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='یوتیوب')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیس بوک')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='کلمات کلیدی')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='لینک نقشه گوگل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='سمت/شغل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نظر و توصیه',
                'verbose_name_plural': 'نظرات و توصیه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
