# Generated by Django 5.0.7 on 2025-12-02 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'ثبت\u200cنام دوره', 'verbose_name_plural': 'ثبت\u200cنام\u200cهای دوره'},
        ),
        migrations.AlterModelOptions(
            name='quizoption',
            options={'ordering': ['order'], 'verbose_name': 'گزینه', 'verbose_name_plural': 'گزینه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='initial_form_data',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='حداکثر تعداد تلاش'),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.PositiveIntegerField(default=50, verbose_name='حداقل نمره قبولی (درصد)'),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz_time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='زمان آزمون (دقیقه)'),
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مدت زمان'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='can_retake',
            field=models.BooleanField(default=True, verbose_name='می\u200cتواند دوباره امتحان دهد'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='پاسخ\u200cها'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='درصد'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, verbose_name='زمان صرف شده (ثانیه)'),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='certificate_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='کد مدرک'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=32, unique=True, verbose_name='کد مدرک')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='courses.enrollment', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name': 'گواهینامه',
                'verbose_name_plural': 'گواهینامه\u200cها',
                'ordering': ['-issued_at'],
            },
        ),
    ]
