# Generated by Django 5.0.7 on 2025-12-02 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام بخش')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('section_type', models.CharField(choices=[('featured', 'اخبار ویژه'), ('latest', 'آخرین مقالات'), ('promotions', 'پیشنهادات ویژه'), ('tips', 'نکات و راهنما')], default='latest', max_length=20, verbose_name='نوع بخش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('max_items', models.IntegerField(default=6, verbose_name='حداکثر تعداد آیتم\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'بخش خبرنامه',
                'verbose_name_plural': 'بخش\u200cهای خبرنامه',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('color', models.CharField(default='#ff6b35', max_length=7, verbose_name='رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subject', models.CharField(max_length=300, verbose_name='موضوع ایمیل')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='محتوای HTML')),
                ('sent_count', models.IntegerField(default=0, verbose_name='تعداد ارسال شده')),
                ('opened_count', models.IntegerField(default=0, verbose_name='تعداد باز شده')),
                ('clicked_count', models.IntegerField(default=0, verbose_name='تعداد کلیک شده')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('posts', models.ManyToManyField(blank=True, related_name='campaigns', to='blog.blogpost', verbose_name='پست\u200cها')),
                ('sections', models.ManyToManyField(related_name='campaigns', to='blog.newslettersection', verbose_name='بخش\u200cها')),
                ('tags', models.ManyToManyField(blank=True, related_name='campaigns', to='blog.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'کمپین خبرنامه',
                'verbose_name_plural': 'کمپین\u200cهای خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='newsletter_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.newslettersection', verbose_name='بخش خبرنامه'),
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='توکن لغو اشتراک')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اشتراک')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو اشتراک')),
                ('tags', models.ManyToManyField(blank=True, related_name='subscribers', to='blog.tag', verbose_name='تگ\u200cهای مورد علاقه')),
            ],
            options={
                'verbose_name': 'اشتراک\u200cکننده خبرنامه',
                'verbose_name_plural': 'اشتراک\u200cکنندگان خبرنامه',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False, verbose_name='باز شده')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان باز شدن')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='کلیک شده')),
                ('clicked_url', models.URLField(blank=True, null=True, verbose_name='لینک کلیک شده')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان کلیک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.newslettercampaign', verbose_name='کمپین')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.newslettersubscriber', verbose_name='اشتراک\u200cکننده')),
            ],
            options={
                'verbose_name': 'آمار خبرنامه',
                'verbose_name_plural': 'آمار خبرنامه',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'subscriber')},
            },
        ),
    ]
