# Generated by Django 5.2.7 on 2025-11-05 11:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='تصویر اصلی')),
                ('status', models.CharField(choices=[('for_sale', 'برای فروش'), ('for_rent', 'برای اجاره'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده')], default='for_sale', max_length=20, verbose_name='وضعیت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='قیمت')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت (متر مربع)')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='تعداد سرویس بهداشتی')),
                ('location', models.CharField(max_length=200, verbose_name='مکان')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('google_maps_url', models.URLField(blank=True, null=True, verbose_name='لینک نقشه گوگل')),
                ('has_parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('has_garden', models.BooleanField(default=False, verbose_name='باغ/باغچه')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='مبله')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('views_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام نوع')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'انواع ملک',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح تصویر')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='real_estate.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'تصویر ملک',
                'verbose_name_plural': 'تصاویر ملک',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='property_galleries', to='real_estate.propertyimage', verbose_name='گالری تصاویر'),
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='real_estate.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'استعلام ملک',
                'verbose_name_plural': 'استعلام\u200cهای ملک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='real_estate.propertytype', verbose_name='نوع ملک'),
        ),
    ]
